### ISSUE TITLE
Images - Timestamp collisions - images appearing twice

### ISSUE THREAD

**Issue by uansett** [shnergle/ShnergleApp-iOS#1]
If you have a loaded set of images, and the first image in the next batch has the same timestamp as the last one loaded, the first new image will not be loaded (since its not newer than the last). If the times are compared larger-than-or-equal, the same image we had will be loaded twice.

For now: compare timestamps, drop images that were taken the same second in the same area/venue

**Comment by uansett** [comment]
dateID introduced in the imageobject from server. Use it concatenated with the time stamp for the last/first images in batches.

Except the initial batch of images, they do not need to be compared.

**Comment by krzd** [comment]
We now have incremental id's.
