### ISSUE TITLE
Adding a venue to Check-in flow

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#117]
When viewing the 'where was this photo taken?' screen during the 'Around Me' check-in flow, the bottom option should be 'Add venue'.

In this instance, once a venue is added, it should revert back to the 'Where was this photo taken?' screen.

**Comment by krzd** [comment]
we'd also need to ensure that the newly created venue is within the 100m radius.
should we only prevent custom location setting then on the add venue screen or lock it to the current one? although you may want to make tiny adjustments to the location.
or should we break after the creation, saying that the venue is not within the radius and another one needs to be selected? which kind of makes the ux weird.
