### ISSUE TITLE
Show day rather than date on image

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#163]
As the app is only going to show 8 days of imagery, and we don't yet have the buttons to segregate by day, can we change the format  for over 24 hrs ago from:

17/07/2013 19:00

to:

Wed 17 Jul 19:00

Would just make it a bit more intuitive I think and is same character length...

**Comment by krzd** [comment]
The library we are using for the time ago timestamps does not support fully custom fallback formats yet. I have contributed support for that and it will be included in the next release of the library, which should not take too long.
Manual changes in the library would be overwritten by every update with the library manager, so either we wait until they released the new version or we can incorporate it just before submitting it.

**Comment by trigger2896** [comment]
Wait until they update the library; otherwise we will keep tripping ourselves up.
