### ISSUE TITLE
'Following' on profile page goes to 'Promotions' filter view?

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#197]
Ok, so if you look at any of the filters (trending, quiet, following etc), when you go to the profile screen and select 'following' it shows the most recently viewed filter.

**Comment by krzd** [comment]
If I go to following view on the profile page I see the one venue I am following: blueberry bar ...

**Comment by trigger2896** [comment]
so go look at 'trending', then go back to the profile screen and tap 'following'.... it will show you 'trending' (at least mine does...)

**Comment by krzd** [comment]
Ah OK, now I get it, will fix now
