### ISSUE TITLE
Close gap between Inentions numbers and promotion / claim button

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#211]
The gap is a bit big at the moment, can we bring the numbers higher up. The gap between the map and the buttons and the buttons and the numbers looks equal at the moment. The gap between the numbers and the promotion/claim venue button should be the same.

**Comment by krzd** [comment]
Constraints are disconnected again, just need to reconnect.

**Comment by krzd** [comment]
Also affects buttons in staff view, as usual.

**Comment by krzd** [comment]
also close gap between comment and map in unoffical venues (ie no summary)
