### ISSUE TITLE
Images hidden by managers

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#229]
I have used my manager status to 'hide' the photo of Stian having lunch at TechHub. It is hidden in the venue detail, but not on the around me screen....even after going to another screen and then back to around me.

Only way to fix was to reboot the app...

**Comment by krzd** [comment]
Its because its cached until the next app restart

**Comment by trigger2896** [comment]
Is there anyway we can get the cache-load to check for hidden status? Just conscious most people will restart the app once in a blue moon....

**Comment by krzd** [comment]
No we could maybe delete the last cached venue image after reporting something to trigger a new fetch from server, but most of the times it will be an unnecessary refresh. If we have more pictures, there will be more pictures in the cache which will delete older images in the cache anyway as soon as too much memory is used. So i would wait too see how long it will actually stay cached when the app is really being used.

**Comment by krzd** [comment]
Maybe we could override the cached venue image as new ones are loaded within the venue, but dont know how well that would work.

**Comment by trigger2896** [comment]
Well, if we can find a relatively simple way of fixing it, great; otherwise lets wait and see how it pans out in use.
