### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by krzd** [shnergle/ShnergleApp-iOS#236]
STTwitter (on CocoaPods) does support posting tweets. We should try it out.

**Comment by trigger2896** [comment]
Good work Adam! If you guys manage to integrate working twitter sharing to the same degree we have with Facebook by end of Wednesday next week it's beer o'clock again! You all get dinner on me! :-)

**Comment by krzd** [comment]
First successfull tweet from the app, even supports image upload easily. Only need to find out a bit more about authentication/request signing. Let's see...

**Comment by krzd** [comment]
Ah, the current release of that library does not support uploading media, but it has been recently implemented. He now (10 hours ago) declared full Twitter API support, so it smells like a soon release.

**Comment by krzd** [comment]
So, using this library I can make tweets, but authentication must be via Web, which will in the end give a PIN code which then needs to be entered into the app. No user wants to do that.
I managed to tweet an image using System Accounts, though. So in-built libraries, only requirement is that the Twitter Account is setup in iOS. I implemented it in a extremely dirty way, so I will need to redo it.
We can let the user chose in the settings which account to use, so he would be able to switch between personal/venue account or whatever. I know that we had problems with the chooser last time we attempted it, but I think we will figure it out this time.
Does that sound good @trigger2896 ?

**Comment by trigger2896** [comment]
Adam, sounds bloody good. As long as the UX is nice and not too jarring, this is awesome. Looks like next week is going to be expensive! :-)

Rob

Rob Tregaskes
Co-Founder & CEO
E: robert.tregaskes@shnergle.com
M: (+44) (0)7894 995 532
L: http://uk.linkedin.com/in/robtregaskes
T: @robtregaskes
