### ISSUE TITLE
Get rid of the gap on official/unverified view

### ISSUE THREAD

**Issue by krzd** [shnergle/ShnergleApp-iOS#245]
There is a gap between the share button and the intentions, as on this view there is neither a promotion nor a claim button.
Before that the label height was adjusted, but we undid that, as the buttons did not match.

**Comment by uansett** [comment]
is there a venue that comes to mind that is claimed but not official? Just so I have a debug target

**Comment by krzd** [comment]
Blind beggar around my place

**Comment by uansett** [comment]
cheers
