### ISSUE TITLE
Intentions, after intending it should show the numbers even if you re-enter the venue

### ISSUE THREAD

**Issue by krzd** [shnergle/ShnergleApp-iOS#246]

**Comment by uansett** [comment]
Do we want another server connection or more appdelegate vars?

**Comment by uansett** [comment]
I'm going with appdelegate for now

**Comment by krzd** [comment]
server connection, because it should also persist when rebooting the phone/app

**Comment by uansett** [comment]
mhm yeah

**Comment by uansett** [comment]
Do we have the userID accessible somewhere in the app? Or do we need another postreq just for that?

**Comment by krzd** [comment]
we only have the facebook id, but you can just save the user id into appdelegate in login screen controller, at the same place we save the twitter property

**Comment by uansett** [comment]
Can you or someone else do an intention on the venue "T" at your place adam? need to check if I can get only my intentions

**Comment by krzd** [comment]
done

**Comment by uansett** [comment]
Need to update server:
if user_id is specified for venue_rsvps, return only those made by that user (and honouring the time stamps as well).

(without this, all venues which have intentions will display them and skip the "going here?" question.
