### ISSUE TITLE
iOS 7: Fix Sliding View (should not go under status bar)

### ISSUE THREAD

**Issue by krzd** [shnergle/ShnergleApp-iOS#259]

**Comment by krzd** [comment]
Reason why extendUnderEdges and aligning to topLayoutGuide does not work:
TopLayoutGuide is 0 instead of 20 despite a status bar being displayed. I can only assume that it is because they are child view controllers, or maybe it is a bug.

An alternative would be to align to topLayoutGuide and if it is iOS 7 change the constant and add 20 points to make it right. But this does not fully fix it, eg the slider font is misaligned etc. So to really fix it we need to figure out why TopLayoutGuide is 0, maybe a bug in Xcode/SDK/iOS or in ECSlidingViewController. I will mention that there as soon as Apple has released iOS 7 (which is when we regain our freedom of speach I guess haha), as no one seems to have checked that.

Changing to an alternative menu type seems to be a big hassle, but if all fails I guess that would be a solution, but to do it properly it would require to redo those screens.

@uansett

**Comment by krzd** [comment]
Interesting: edgesForExtendedLayout also does not work on LoginScreenController, and also topLayoutGuide is 0 there. It also doesn't work if the AroundMeViewController is used decoupled from the Sliding View. So what is different with the login and sliding view as compared to all others? Any special segue/transition/setting/initialisation/...?

**Comment by uansett** [comment]
Maybe because this is where we initialise the navigation controller? I
think it has no real connection with the login screen controller so
maybe that transition is causing some hiccups. How about adding edge
insets to login as well and we how that goes
