### ISSUE TITLE
mapView on AroundMe has faulty constraints (end of map appears when closing drawer)

### ISSUE THREAD

**Issue by uansett** [shnergle/ShnergleApp-iOS#27]
happens in iOS 6

**Comment by krzd** [comment]
There are no constraints for that anymore, position and size is purely controlled by this line in the method initMap in the AroundMeViewController:

``` smalltalk
_mapView = [[GMSMapView alloc] initWithFrame:CGRectMake(0, 44, self.view.bounds.size.width, self.view.bounds.size.height - 139)];
```

I did not test this way on iOS 6, so just change the height appropriately.

**Comment by uansett** [comment]
Nice, will adapt it to ios6

From:  Adam Hani Schakaki notifications@github.com
Reply-To:  shnergle/ShnergleApp-iOS
<reply+i-15592000-c475d96b4556ed28b7cce0485ebe794753fea326-1151317@reply.git
hub.com>
Date:  Saturday, 15 June 2013 15:09
To:  shnergle/ShnergleApp-iOS ShnergleApp-iOS@noreply.github.com
Cc:  Stian Johansen stian.uansett@gmail.com
Subject:  Re: [ShnergleApp-iOS] mapView on AroundMe has faulty constraints
(end of map appears when closing drawer) (#27)

There are no constraints for that anymore, position and size is purely
controlled by this line in the method initMap in the AroundMeViewController:

_mapView = [[GMSMapView alloc] initWithFrame:CGRectMake(0, 44,
self.view.bounds.size.width, self.view.bounds.size.height - 139)];
I did not test this way on iOS 6, so just change the height appropriately.

‹
Reply to this email directly or view it on GitHub
<https://github.com/shnergle/ShnergleApp-iOS/issues/27#issuecomment-19496971

> .

**Comment by krzd** [comment]
I assume this happens, because for iOS 7 we are running in fullscreen, so using the following should fix it:

``` smalltalk
_mapView = [[GMSMapView alloc] initWithFrame:CGRectMake(0, 44, self.view.bounds.size.width, self.view.bounds.size.height - 119)];
```

**Comment by uansett** [comment]
Will check out, and modify on Monday anyways for iphone 5. thanks

From:  Adam Hani Schakaki notifications@github.com
Reply-To:  shnergle/ShnergleApp-iOS
<reply+i-15592000-c475d96b4556ed28b7cce0485ebe794753fea326-1151317@reply.git
hub.com>
Date:  Saturday, 15 June 2013 15:11
To:  shnergle/ShnergleApp-iOS ShnergleApp-iOS@noreply.github.com
Cc:  Stian Johansen stian.uansett@gmail.com
Subject:  Re: [ShnergleApp-iOS] mapView on AroundMe has faulty constraints
(end of map appears when closing drawer) (#27)

I assume this happens, because for iOS 7 we are running in fullscreen, so
using the following should fix it:

_mapView = [[GMSMapView alloc] initWithFrame:CGRectMake(0, 44,
self.view.bounds.size.width, self.view.bounds.size.height - 119)];
‹
Reply to this email directly or view it on GitHub
<https://github.com/shnergle/ShnergleApp-iOS/issues/27#issuecomment-19496996

> .
