### ISSUE TITLE
Instagram integration

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#281]
I hear people wanting Instagram integration constantly, so I think its something we should investigate pretty urgently.

My thinking is that it should be the same as Facebook and twitter sharing....

**Comment by trigger2896** [comment]
I should add that from looking at the Instagram API documentation its not very clear how you post to Instagram, it is mostly focussed on surfacing data from Instagram. Having said that, there are plenty of third party Instagram clients about so you must be able to....

**Comment by krzd** [comment]
Looking at their API it does not seem possible to post images to instagram.
The only way appears to display the picture with a share menu (the box with the arrow where you can select where to share it), which would then open eg the Instagram app and you could then upload it from there. But that menu would probably also allow to select other apps and does not really fit into our current UX.

**Comment by trigger2896** [comment]
So how do the third party instagram clients do it? (Think Windows Phone which has a number) I reckon its worth registering on their dev program to see what we can do. If necessary I am not averse to contacting their dev team direct and asking for access....

**Comment by krzd** [comment]
I checked with a few posts, and Instagram's position is to not allow third-party apps to allow photo uploads, for a few reasons.
Some apps allow you to upload to Instagram, those are directly cooperating with Instagram. Example of such a partnership: http://www.fastcompany.com/1824797/exclusive-hipstamatic-instagram-unveil-photo-sharing-partnership
So the only way would be to talk to Instagram and see what we can do. I could not see what the partnership involves.

**Comment by krzd** [comment]
Also some Windows Phone apps use private APIs for uploading images, which is against of the Terms of Use, and thus leads to that: http://gigaom.com/2013/07/30/instagram-update-is-blocking-photos-uploaded-by-third-party-apps-on-windows-phone/

**Comment by krzd** [comment]
I guess this can be closed until Instagram open its API or we are big enough to partner with them.
