### ISSUE TITLE
iOS 7 Filter integration

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#282]
A lot of people seem to like filters, and they are included in iOS7, so we should work them into the photo flow for iOS 7 (along with square/rectangle)....

**Comment by krzd** [comment]
Current documentation does not tell me about a way to enable those controls (as in iOS 7 those controls are on the screen where the picture is taken). As soon as it becomes clear how to do it, we can.

**Comment by krzd** [comment]
Does not seem possible. And the only library for filters which is close to what we could use (at least what I have found), is around 100 MB big, so there is no point including that.
Maybe Apple will change that at some point or we need to built something custom (there are some frameworks for that, but nothing we should do anytime soon as it is a lot of work).
The iOS 7 filters are not even spectacular anyway.
