### ISSUE TITLE
Check what level users are on from the server, and place head accordingly

### ISSUE THREAD

**Issue by uansett** [shnergle/ShnergleApp-iOS#29]

**Comment by krzd** [comment]
ProfileViewController.m, line 70 (as of commit 310095c) reads:

``` smalltalk
NSMutableString *params = [[NSMutableString alloc] initWithString:@"facebook_id=549445495"]; 
```

But should read:

``` smalltalk
NSMutableString *params = [[NSMutableString alloc] initWithString:[NSString stringWithFormat:@"facebook_id=%d", appDelegate.facebookID]];
```

Obviously appDelegate needs to be declared. But as of now it will only check the rank of whoever is id  549445495 instead of the current user. The latter will do it for the current user.

**Comment by uansett** [comment]
Was a temporary testing insert from yesterday, is removed in current commit

**Comment by uansett** [comment]
Thanks for the heads up anyway :)
