### ISSUE TITLE
Autoreleased Objects and Explicit Allocation - Convert Where Appropriate

### ISSUE THREAD

**Issue by krzd** [shnergle/ShnergleApp-iOS#296]
Objects created by convenience methods (eg `[UIImage imageWithData:data`) are autoreleased objects. Those are not cleared until the end of the autorelease pool, which in our case is when the app exits. Using explicit allocation (eg `[[UIImage alloc] initWithData:data]`) should lower our memory usage significantly.
Sometimes convenience methods are useful, for example when loading images which are part of the user interface. This way those images are, at least in a way, cached. Anything which loads big data, data which is not needed often or changing data should be created using explicit allocation.
I will convert implicit allocation to explicit where appropriate. It seems that my understanding, that those methods were purely convenience methods and behave exactly the same under ARC, was wrong. So I just want to ensure that you know about that @uansett @harshirulz.
This should also enable us to load higher resolution pictures throughout the app, although I cannot exactly say until this is done @trigger2896.

**Comment by uansett** [comment]
Nice find @krzd.
Does that mean we have to explicitly deallocate them as well when changing
views? Or will their lifetime be tied to the view controller's
automatically?

**Comment by trigger2896** [comment]
Ok cool, good work Adam; let's see how it works out...

**Comment by krzd** [comment]
@uansett: When using explicit allocation under ARC, the compiler will add `retain` and `release` statements as appropriate, so you do not need to deallocate them explicitely, in fact you cannot. The compiler will determine the appropriate place, be it when changing views or later or even earlier. For autoreleased statements the compiler will add `autorelease`, so it acts as if `retain` was added but `release` is never called until the autorelease pool ends, in our case when the app exits. So nothing changes other than not using convenience methods, ARC handles everything, it is just the difference between autorelease and normal release. It is the same as without ARC just that you dont have to retain and release because the compiler does it, but the difference still exists.

**Comment by uansett** [comment]
All right, thanks. Very clear.

**Comment by krzd** [comment]
Addendum: Some convencience methods actually act as shortcuts for `[[Class alloc] init]` and therefore are fine, for example `[NSMutableDictionary dictionary]` or `[NSDate date]`. Could only find UIImage as a problem in our codebase right now, but I may have overseen something.
