### ISSUE TITLE
Google Maps - Attribution

### ISSUE THREAD

**Issue by krzd** [shnergle/ShnergleApp-iOS#304]
The Google Maps attribution must be visible on Around Me (cf Terms of Use).

Also if someone knows about the current limits: In March there was a limit of 100,000 map loads per day, there still are request limits for certain request (varying from 2,500 to 25,000 depending on request), and we have had already 2,000 request a day on the 15 August. So we should find out whether the load limit is still in effect and whether we could be affected by the limits in some time.

**Comment by trigger2896** [comment]
What happens when we reach our limit - do we have to pay?

**Comment by krzd** [comment]
If the limits affect us, then it would stop working until we pay. There is a grace period of 90 days before it will stop working, though.
Depending on which limits are in place, we should optimise the application to not reach them or enable billing, I guess.

**Comment by trigger2896** [comment]
ok cool - optimisation followed by some 'wait and see' seems like the best plan...
