### ISSUE TITLE
'Thank You' screen after checkin/photo upload

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#305]
Either a screen or a popup that:
- Says thank you for adding to the Shnergle Community or thank you for spreading the word after a successful upload/share.
- Confirms everything has uploaded properly

-Highlights how many points have just been earned

This should be what the user is sent to just after the upload/share has completed. Am not sure what it should look like yet, but just put it up here to track whilst I think about it...

**Comment by krzd** [comment]
Maybe combine that with the promotion redemption alert, which displays the pass code if the check in was also a redemption.

**Comment by trigger2896** [comment]
Yeah, I think the whole thing needs a slightly more thought through UI.... will have a play and see what I come up with.

**Comment by trigger2896** [comment]
Maybe something like this....

**Comment by trigger2896** [comment]
![thank you screen](https://f.cloud.github.com/assets/3640474/1108450/2f0e6df6-196f-11e3-8f3b-466aadb39cea.png)

**Comment by krzd** [comment]
To devs: we should use GCD to perform uploading and sharing in parallel and then wait for all threads to finish before we show that screen. That way at that point sharing is actually completed and we can reliably determine the score. This should also cleanup our current code mess on the share screen.

**Comment by uansett** [comment]
Do we have that graphic somewhere? edit: the checkmark I mean

**Comment by trigger2896** [comment]
It is just the tick from glyphicons with the same green as the checkin button...

**Comment by uansett** [comment]
Done. need to verify that the user actually shared to facebook or twitter.
