### ISSUE TITLE
Onboarding Process

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#307]
We should have some initial screens (I need to think about what exactly) that should 'onboard' new users into the app. No more than 5 screens, they might include:
1. UI Tips:
2. Around me map expander, map ring, and around me button
3. Slide up tray on venue view
4. Gamification highlight
5. Promotions and official venues
6. The final bit would be to take a photo to get their first check-in...

Thoughts?

**Comment by krzd** [comment]
Is a really nice thing to do, but quite sophisticated to implement ... But yes that should be good to attract users to use the app, but we should ensure that there is always a possibility to skip that 'tutorial' as some users might not want to go through that tutorial or parts of it (eg not everyone might want to check in straight away, especially if they are installing it at home).

**Comment by trigger2896** [comment]
Agreed.

**Comment by krzd** [comment]
What about making it just a series of screenshots with a bit of text below each of them, where you can swipe through with a cancel button somewhere (cf Barclays app)? That shouldn't be too hard I guess.

**Comment by krzd** [comment]
Just found an easy to use and good looking library for doing a screenshot show, would look like that: http://icepat.github.io/ICETutorial/
Could do some screenshots, highlight what we want to show and write a short line about it or so.
Would be easier than creating a whole onboarding flow and probably quicker (maybe less annoying) for the user. That is how Path and Barclays do it anyway.
Thoughts?

**Comment by trigger2896** [comment]
Looks good, lets do this with ios7 screenshots once its out. We will need to do a whole load of new screenshots for ios7 in iTunes anyway...

**Comment by krzd** [comment]
When exactly should this appear? After the acceptance screen if it is a new user or maybe whenever it was freshly installed or ...? Should it also be accessible somewhere else for 'later'?

**Comment by trigger2896** [comment]
Yep - straight after policy acceptance, and before going to the around me screen. I think the criteria should be if new user - if we make significant changes to the UX in future versions of the app we can change that criteria to make sure everybody sees it. I don't think it should b accessible later, unless we put it as an option on the help screen?

**Comment by krzd** [comment]
Ok, I would maybe put it on the help screen for existing users and impatient users who just skipped it but want to see it again or so.

**Comment by krzd** [comment]
I prepared the tutorial, but the library still seems to have some issues. Seeing that he is relatively active on it, I would suggest waiting for the next release (where parts of it are already fixed). Otherwise, we have to fix them ourselves.

**Comment by trigger2896** [comment]
Lets give it a few days and see before fixing ourselves. Has he indicated any release timelines?

**Comment by krzd** [comment]
No, but based on recent releases, I can well imagine that it would be before our next release. Or at least by then, that he has fixed the issues in the main repository, which would already be helpful.

**Comment by trigger2896** [comment]
Cool. Yeah waiting a few days sounds sensible...
