### ISSUE TITLE
Change 'where is this place' map segment to navigation tool using Apple Maps

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#322]

**Comment by krzd** [comment]
Navigations still cannot be embedded it seems.

Alternative 1: Try to find a way to display venue and current location and let the person without any line which shows the way. If that is not possible in a reasonable way, do Alternative 2 or 3.
Alternative 2: Provide buttons to open Apple Maps with the coordinates set for navigation.
Alternative 3: Do Alternative 1 and 2, unless Alternative 1 is not possible in a reasonable way, then just do Alternative 2 or Alternative 1, which both will result in Alternative 2.

(I hope made enough references to the alternatives within them ;))

//edit: http://stackoverflow.com/questions/12636707/how-can-i-get-direction-on-an-iphone-ios-6-app-in-xcode-from-a-to-b/12789896#12789896

**Comment by trigger2896** [comment]
Alternative 2, unless they are in London or NY in which case use city mapper! :-)
http://blog.citymapper.com/post/59578777734/launching-citymapper-directions-from-apps-and-the-web
