### ISSUE TITLE
Include a leaderboard showing the scores of your FB friends

### ISSUE THREAD

**Issue by krzd** [shnergle/ShnergleApp-iOS#334]

**Comment by krzd** [comment]
From where should that leaderbord be accessible?

**Comment by trigger2896** [comment]
Change the profile text 'How can I improve my Shnergle score?' to just 'How do I improve?'

Then nudge it down a bit and replicate (in the same style) just above it: 'How do I compare?'

I'll upload a mockup of what the screen should look like in a bit...

**Comment by trigger2896** [comment]
Show the top 10 in something simple like this:

![leaderboard](https://f.cloud.github.com/assets/3640474/1153249/8989ad14-1f1d-11e3-9308-a7228bf5a42b.jpg)

**Comment by krzd** [comment]
Unfortunately our current database design does not allow us to do this efficently. Even if you just have 5 friends using shnergle and we only query the scores of them, that would be already over 50 database query, which our database cannot really handle (seeing the connection failures) and it would take too long.
I would suggest closing it for now, until we have done the neccessary database changes (probably migrating to another type of database).

**Comment by trigger2896** [comment]
Seems fair enough. For my own understanding, am I right in think there would need to be two layers of queries;
1 to identify the actual Facebook friends who were users on the system
And
1 to calculate their scores and so who should go at the top.
What does Facebook actually provide us, just the friends list?

**Comment by krzd** [comment]
Facebook provides us a friend list, according to Stian we can filter that by who is using the app.
But to calculate the score we need about 10 queries, eg one to get the number of posts, one for the number of venues shares, another one for the number of post shares etc pp
That's was causing the trouble...
