### ISSUE TITLE
Limit characters for venue name

### ISSUE THREAD

**Issue by krzd** [shnergle/ShnergleApp-iOS#335]
just do not allow to enter more characters than this limit (thats what we do/did somewhere else). this ensures that there is always some space for the text in tweets and long names are cut off in most places anyway, so too long names just do not make sense, I guess. what should that limit be? 40 characters?

**Comment by trigger2896** [comment]
I just checked a couple of the longest names and they were 29 characters, so I think 40 is a pretty safe bet....
