### ISSUE TITLE
Manager suppress bad images with one click

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#34]
When looking at a close-up of an image in a venue that a user manages, the 'report image' button should display as 'hide image' and the manager should be able to hide the image from the feed with one press (unlike the standard - 3 users click report, server hides the image).

**Comment by krzd** [comment]
requires #65

**Comment by krzd** [comment]
@trigger2896 Can a manager un-suppress an image whilst he is still on the page with the post?
Answer: No, pop afterwards.
