### ISSUE TITLE
Check location before enabling upload

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#341]
We need to delete the photo that Sophie Mantell just added to the Rockingham Arms. Also, the upload button (after taking the picture) should only be usable if still within 111m of venue.

**Comment by krzd** [comment]
Deleted, not sure if checking again after the step is a good idea. Main reason we did it before, is that if you are ablet oc heck in and start the process, but for some reason your location information gets bad or wrong (eg you are moving while posting uploading, you are going inside, etc pp), the user might be annoyed that he has taken the picture but has no way to upload or share it, especially if he disabled the option to save the images locally.

**Comment by trigger2896** [comment]
Fair point. Would a check followed by a prompt (are you sure this photo is of...?) be too complex and disruptive to the UI do you think?

**Comment by krzd** [comment]
Before I would have said no, but now we also have the thank you screen, in addition to potential Facebook and Twitter screen, I think it will be too much.
I suggest monitoring if that happens often and if it does we should maybe find a solution, if not I would just leave it as it is.

**Comment by trigger2896** [comment]
Fair point. We blatantly can't monitor so let's just close the issue

**Comment by krzd** [comment]
By monitor I did not mean active monitoring, but we might notice it if it happens. But for now I agree to closing.
