### ISSUE TITLE
Icon in top left corner of venue preview indicating if followed

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#348]
Let me play with what this might look like...

**Comment by krzd** [comment]
Earlier, when we had the star as inidcator for a promotion, I always thought that it was meant to be for favourites.
So what about using a similar corner, but now really with a star this time? (glyphicons_049_star@2x.png)
Or maybe do something with the bookmark symbol, but I guess that will be harder to get right. (glyphicons_072_bookmark@2x.png)
[Filenames correct for Glyphicons 1.8]

**Comment by krzd** [comment]
Actually the bookmark does not look bad:
![untitled](https://f.cloud.github.com/assets/1003886/1184367/e670d77a-2245-11e3-96a4-74166aae0534.png)

**Comment by trigger2896** [comment]
Can we see what it looks like in shnergle orange? At the same time can we see what the promotion thing looks like in shnergle orange? Neither are very visible at the moment...

**Comment by krzd** [comment]
I personally find the promotion corner quite visible in black/white. The bookmarks is not, but it could be improved by just adding a white line along the shape of the bookmark, just with 1-2 pixels gap, if that makes sense.
This is not very properly done  now, but just to give an idea how it would look like in orange:
![e670d77a-2245-11e3-96a4-74166aae0534](https://f.cloud.github.com/assets/1003886/1185518/b27c2b7c-22ae-11e3-8524-eb7c6ddeb030.png)

**Comment by trigger2896** [comment]
Is that the right orange? 255, 102, 0? I am pretty sold on using the bookmark tab from glyphicons, just not sure about colour. I definitely think black is a no go, as have had multiple feedback that the promotion marker isn't clear enough. How about we put the bookmark in the same green as the 'tap to follow' and checkin buttons (102,204,0), and the promotion marker in the same blue as the promotion icon (2,168,223)?

I think we need toplay with it for a little while and work out what we like and what we don't colour wise...

**Comment by krzd** [comment]
It certainly is the right orange, I 'picked' it from the launch image background.
I do not have a proper image editing program here, so I guess it would be easier if you just play around with the colours and send me a coloured version of the icons once decided?

**Comment by trigger2896** [comment]
Ok, cool. I'll get some files over to you at some point, though not sure when exactly as just about to head off for the weekend! :-)

**Comment by krzd** [comment]
That ok?
![untitled](https://f.cloud.github.com/assets/1003886/1191422/2252815a-2451-11e3-8fc9-af098e6254e7.png)

**Comment by trigger2896** [comment]
Yeah, lets go with that for a while and see what we think over a few days...
