### ISSUE TITLE
User Intention Buttons on Venue pages

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#35]
Change text to:
'Maybe', 'Going' & 'Checked In'

Add question text above boxes:
'What are your plans? Are you going here?'

The numbers should be referencing the table of 'users who have indicated intentions or checked in' (not actual name!) on the database for that venue for that 24hr period. If the user has put themselves into any category (by tapping the button for the 'Maybe' and 'Going' options, or by checking in for the 'Check In' Option) on the server, the app should register that in the app by making the grey square in question darker.

**Comment by trigger2896** [comment]
Rather than adding the questions, change the grey squares to buttons so that it is more obvious. Keep the size and 'dark grey if pressed' colours that have now been implemented.

**Comment by trigger2896** [comment]
What about putting the buttons on the same level as the promotion, share and comment buttons, so that the maps scrolls up underneath the intentions buttons (they would sit just below the merchant promotion)? This keeps all 'user activity' in the same place and makes it more obvious that the buttons should be interacted with....
Then the scrolling view can just have the maplet, then the message from the venue owner, then the comments section.

**Comment by uansett** [comment]
We'll need to restructure quite a bit if we want intentions to be under the promotions mainly because of the size on iPhone 4/4s - What I have tried now is keeping them in the same spot, but making them a bit more memorable... maybe too memorable, but they do attract attention? They are in "Crazy Red", "Funky Yellow" and "Check-In-Green".

**Comment by trigger2896** [comment]
Liking the new position, what if we change them to look like this?
![intention button options](https://f.cloud.github.com/assets/3640474/704155/e6049ff4-ddb9-11e2-93b4-3c6c54748c65.png)
