### ISSUE TITLE
Change Emphasis on thank you screen

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#350]
So I was chatting to the chap next to me, and he highlighted that in games when you get more points, the game makes a big deal out of it. At the moment we have a tiny little bit of text with the number of points; the emphasis needs to be on the points not the success.

Let me play about with what this should look like and upload something...

**Comment by trigger2896** [comment]
Something like this perhaps:

![thank you screen](https://f.cloud.github.com/assets/3640474/1188080/f7931e8c-23b2-11e3-96a0-eb788cc3dda4.png)

**Comment by uansett** [comment]
Sure you want to leave out the checkmark? it livens up the page a bit I think! But otherwise this is much better. Will look into that

**Comment by uansett** [comment]
Why is it not-yet-doable?

**Comment by krzd** [comment]
I tagged it no yet doable because there was input missing on how it should look like, which is now there ...

**Comment by uansett** [comment]
right, of course :)
