### ISSUE TITLE
Connection Failure

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#352]
This is caused by someone not allowing access to facebook. You can then go into the settings - > look at facebook settings and turn access back on.

This didn't work with Noah on the iPhone queue yesterday, but just worked fine with the chap next to me at work. Is there any way we can provide a prompt message to segregate this from other connection failures? Perhaps call it a 'Facebook Connection Failure', then the other options could be 'Server Connection Failure' or 'Database Connection Failure'?

**Comment by krzd** [comment]
We can easily distinguish a Facebook error from a server error, but it is harder to get the accurate reason (database or not). I would suggest in the case of a Facebook error, to provide a slightly longer description which also outlines the possible fixes ('Could not log in with Facebook. Ensure access is enabled in Privacy/Facebook settings and your Facebook account is properly set up.' or so).

**Comment by trigger2896** [comment]
Yep, like it - go with that....
