### ISSUE TITLE
Fix schizophrenia about staus bar overlay/underlay

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#356]
Status bar is an overlay in around me, but a black bar in the venue view - looks schizophrenic and results in awkward Segway between views (look at the top of the screen)

**Comment by krzd** [comment]
I am aware that all views which dont have the sliding menu work significantly different regardig navigation and status bar. I did not yet figure out how to make it consistent or better get the transitions right. Will be fixed as soon as we figured that out.

**Comment by trigger2896** [comment]
Yep, I guessed that was the case.

**Comment by krzd** [comment]
That's the only fix I have right now:
- CustomBackViewController.m in viewDidLoad:
  `
  self.edgesForExtendedLayout = UIRectEdgeAll;
  self.extendedLayoutIncludesOpaqueBars = YES;
  self.automaticallyAdjustsScrollViewInsets = NO;
  `
- Then moving all content down (depending on what element either 64 or 20 points)
- Setting background colour of all views to the right grey

Is neither the right way to do it nor would it be easy, as all views need to be changed significantly.
Anyone any other idea?

**Comment by krzd** [comment]
Changed a few things, is probably the clsoest we can get without changing too much.
All views should be tested, some elements might be too high/under the statusbar.
Also the claiming, redemption and adding a venue where you are working flows should be tested.
