### ISSUE TITLE
1.6 completely broken, but restarting (twice) seems to fix

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#371]
I have no idea how it happened, but earlier the side menu was completely unresponsive (when you tapped on the options they light up but you didn't go to the relevant view). When you went to different screens the top bar slide over as it should, but the main screen was just greyed out. I closed down the app twice and it eventually seems fixed. It was working fine last night so not sure what caused it...

**Comment by krzd** [comment]
This was the Facebook bug I was talking about, I experienced that since yesterday evening as well. Downgrading the SDK again should fix it. Let me know if it happens again to see if it is a permanent bug.

**Comment by trigger2896** [comment]
ok, will do.
