### ISSUE TITLE
Remove RSVP from scoring system

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#384]

**Comment by krzd** [comment]
I would leave it, removing the aspects from the server might conflict with older app versions. As the points are calculated over the last 30 days only it should not make any big difference anyway or would it?

**Comment by trigger2896** [comment]
Is there any way we can remove it from just the client and it still show the right score?

**Comment by krzd** [comment]
I could remove it from the calculation of the end score and ranking.

**Comment by trigger2896** [comment]
perfect

**Comment by krzd** [comment]
To prevent conflicts it will display that you have 0 rsvps on the score screen in older versions.
