### ISSUE TITLE
Space between Map section and intentions section in venue view

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#44]
This gap should be as small as possible. Is it possible to dynamically scale it depending on what the merchant has written in his field? Likewise its ok if looking from a manager perspective as there is a button, but from a 'normal', 'following' or 'staff' perspective there should be no gap where that button is.

**Comment by uansett** [comment]
Note to devs:
Fixed map gap issue, minimised gap between intention boxes and tonight-text. So far not been able to change constraints on-the-fly inside the app.
