### ISSUE TITLE
'Check-In' Button should change to 'Upload' once checked in at a venue

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#50]
Within any 24 hour period, once the user is 'checked-in' once, the 'check-in' button should say 'upload'. This encourages them to upload more imagery (without thinking they are checking in multiple times).

This also solves the venues staff/manager issues - they can check in the first time they get to work (they are users too right!) and then keep 'upload'ing throughout their shift.

**Comment by krzd** [comment]
requires #86
