### ISSUE TITLE
Layouts for 'Official' Venues and 'Unofficial' Venues

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#57]
So at the moment we have been tweaking the UX for an official venue, complete with promotions etc.
We will also need a layout for an unofficial venue - that has not yet been claimed by its owners.
The exact layout will be dependant on how we end up with the official venue view, but it will be missing the promotion section, will be missing the 'message from the bar owner' section and should include a big red button about the size of the promotion button saying something along the lines of:
'Do you work here? Control your brand and engage with your customers - Claim this venue'
We can work out the specifics once we are happy with the official layout.

**Comment by krzd** [comment]
requires #87
