### ISSUE TITLE
Facebook comment broken

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#84]
Just checked in at Blueberry Bar, and the Facebook post said Null a lot!

**Comment by krzd** [comment]
# ShareViewController.m, Line 107

## Is

``` objective-c
    action[@"message"] = [NSString stringWithFormat:@"@[%@:%@]", selectedFriends[0][@"id"], selectedFriends[0][@"name"]];
```

## Should

``` objective-c
    action[@"message"] = [NSString stringWithFormat:@"%@ @%@", _textFieldname.text, appDelegate.activeVenue[@"name"]]; 
```

## Reason

Commit 4a60ab8273d4bf3c8de1c4c452d11579e77767e6 introduced that for debug reasons and has been forgotten.
