### ISSUE TITLE
Staff management implementation

### ISSUE THREAD

**Issue by uansett** [shnergle/ShnergleApp-iOS#89]
Implement staff management - fetch names from server and appoint/delete user IDs using the staff management form

**Comment by krzd** [comment]
- ~~Disable promotion switch and set to 'on' when type is manager~~
- ~~Otherwise make sure switch represents correct status~~
- ~~Request to save changes~~
- ~~Request to delete (needs server side implementation as well)~~
- Add staff

**Comment by krzd** [comment]
@trigger2896 What should the 'add staff' process look like?

**Comment by trigger2896** [comment]
Think along the lines of the 'with' section of FB sharing.
There needs to be an 'add' button in the top right of the staff page (that looks like the 'with' button on the share page). That add button should realistically bring up a search page; we can't have a full list of users as there is no 'friends' concept to whittle it down. When the search returns names, it should bring up profile pic, first name and last name. You then tap the name and a confirmation pop up appears 'are you sure you want to add xxxx as a member of staff?'. Click ok and you go back to the staff screen where they are now on the list.

Is that helpful?

**Comment by krzd** [comment]
It is helpful, but I don't think we can do that. We have an opt out, so that managers can't see a top 5 user, but the manager can find all users through the staff menu? Yes, he would have to search, but searching for 'a' would already reveal a lot of users, including their full first and last name and profile picture. Setting a minimum character length for names is also not helpful, with people having names like 'Yi Li'.
So the only ideas I have to let a manager add someone to the staff, without seeing all users is that he can only add an user when he knows either the Facebook ID or username. As noone knows their ID, I guess the full facebook username seems way better.
Any kind of search would probably be a breach of privacy (policy), so it needs to be something 'full' and unique.

**Comment by krzd** [comment]
Oh, and email would be another possbility, which also is Facebook-agnostic, which is good when we have Twitter integration as well.

**Comment by trigger2896** [comment]
I don't think searching all users would be a breach of the privacy policy. Search in this context merely confirms that someone exists on Shnergle, in the same way as search confirms people exist on Facebook. It would only be a breach of privacy if their personal profile came up showing where they had been. Just returning the name and profile pic doesn't give the merchant any ability or incentive to contact them, for all he knows they could be in Outer Mongolia.

To really play devils advocate, if the merchant did the same search in Facebook he would get more results (1bn users) and could find out loads more about them...

Thoughts?

**Comment by krzd** [comment]
It is just that it seems ridicolous to me that you can opt out of top 5, but still be seen in the search, albeit without ranking.
Yes, Facebook delivers more results, but they have an option to opt out of appearing in the search results. So it is your decision wether people can find you. Such an option would not make sense for us.
Just wanted to put the concern out there for consideration. I am fine with any way.

**Comment by krzd** [comment]
Sorry, you can't opt out of the search (anymore?). Anyway my main concern is the point of opt out of top 5 but still be able to be seen.

**Comment by trigger2896** [comment]
All fair points. The difference between the search and top 5 is that the top 5 indicates you frequent a venue regularly. Therefore top 5 has not just name and photo, but location data (and an indication of time frequency) associated with it, making it more of a privacy invasion.

The search however just brings the details of people, not their location or what time they are there, a much lower privacy invasion.

For example, if you searched Jane Smith, you may get 25 Jane Smiths all with different photos. You wouldn't know anything about them, and would probably have to ask the Jane in question what her profile pic was.

If however you saw a Jane Smith in the top 5 list, you would know she came to your venue regularly and could introduce yourself to her (which she may not want). You could also use your knowledge of her location to narrow down the options on Facebook etc.

Some that make sense?
